INSERT INTO
    public.types_table(
        bigint_field,
        smallint_field,
        numeric_field,
        double_field,
        boolean_field,
        varchar_field,
        char_field,
        text_field,
        date_field,
        time_timezone_field,
        time_field,
        enum_field,
        array_field,
        xml_field,
        json_field,
        composite_field,
        money_field,
        byte_field,
        point_field,
        line_field,
        varbit_field
    )
VALUES
    (
        99999999999999999,                  --        bigint_field,
        30000,                              --        smallint_field,
        123456.789,                         --        numeric_field,
        123.456,                            --        double_field,
        false,                              --        boolean_field,
        'string',                           --        varchar_field,
        'some example string of length 32', --        char_field,
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        '2000-01-01',                       --        date_field,
        '00:00:00 +03:00',                  --        time_timezone_field,
        '00:00:00',                         --        time_field,
        'first_value',                      --        enum_field,
        '{123, 234, 345, 456, 567}',        --        array_field,
        '<note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>help me pls</body></note>', --xml_field,
        '{"value": "Close", "onclick": "CloseDoc"}', -- json_field,
        ROW(123, '{543, 123}'),             --        composite_field,
        '1000',                             --        money_field,
        '\x45CFF3',                         --        byte_field,
        '(1.234, 3.432)',                   --        point_field,
        '((23.312, 86.432),(12.321, 4.321))', --        line_field,
        '1010001100110'                     --        varbit_field,
    );